Update mccs.yml
arcnmx/mccs-rs pull request #1
Opened 2022-10-23 13:00 UTC by Toxblh

Add USB-C ports
Source https://github.com/alin23/Lunar/blob/master/Lunar/DDC/DDC.swift
Checked on DELL U4021QW

2022-10-23 17:15 UTC, arcnmx requested changes

2022-10-23 17:15 UTC, arcnmx commented on db/data/mccs.yml
> -  - value: ">=0x13"
`>=0x13 && <0x19` will still need to be marked reserved

2022-10-23 17:15 UTC, arcnmx commented on db/data/mccs.yml
> +    desc: USB-C / Thunderbolt 1
`=0x1A` still reserved too!

2022-10-23 17:15 UTC, arcnmx commented on db/data/mccs.yml
> +  - value: ">=0x1B"
`>0x1B` or `>=0x1C`

2022-10-23 17:16 UTC, arcnmx commented
So I think it just needs to be something like `>=0x1C || (>=0x13 && <0x19)`?

2022-10-23 20:09 UTC, Toxblh commented
Yeah, question. Better cover all gaps in single value, or like I did in last commit?

2022-10-23 20:33 UTC, Toxblh commented
I think better to combo in single. Agree with you.

2022-10-26 10:31 UTC, Toxblh commented
@arcnmx Could you pls review?

2022-10-26 20:17 UTC, arcnmx requested changes
Sorry, I've been recovering and busy. I've got the [CI working again](https://github.com/arcnmx/mccs-rs/actions), and moved an old incomplete WIP commit to another branch, if you wouldn't mind rebasing onto the new master?

2022-10-26 20:17 UTC, arcnmx commented on db/data/mccs.yml
> +  - value: ("=>0x13" && "<=0x18") || "=0x1A" || ">=0x1C"
I'm pretty sure this needs to be a single yaml string, quotes like this will throw off the parser.

2022-11-14 16:45 UTC, merged